.\" Manpage for noisetest.
.\" Contact info@thefirstkube.net for comments or help.
.TH man 1 "May 2022" "1.0.0" "noisetest man page"
.SH NAME
noisetest \- simple lightway library for writing unit tests.
.SH SYNOPSIS
noisetest
.SH DESCRIPTION
noisetest is a simple lightway library for writing unit tests.
.SH OPTIONS
noisetest does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Apostolos (info@thefirstkube.net)
